version: "2.1"

services:
  nginx:
    image: nginx:1.15
    depends_on:
      - spa
      - api
    volumes:
      - ./services/nginx/sites-enabled:/etc/nginx/conf.d:delegated
    volumes_from:
      - spa
      - api
    ports:
      - 80:80
  api:
    image: node:10
    container_name: api
    working_dir: /app/api
    entrypoint: ["/app/services/api/scripts/run.sh"]
    command: ["npm", "run", "start:dev"]
    external_links:
      - api.mycraft.localhost
    volumes:
      - ./api:/app/api:cached
      - ./services:/app/services:delegated
    ports:
      - 3000:3000
  spa:
    image: node:10
    container_name: spa
    working_dir: /app/spa
    entrypoint: ["/app/services/spa/scripts/run.sh"]
    command: ["npm", "start"]
    external_links:
      - mycraft.localhost
    volumes:
      - ./spa:/app/spa:cached
      - ./services:/app/services:delegated
    ports:
      - 4000:4000